### ISSUE TITLE
Android not tracking events, works for Ios

### ISSUE THREAD

**Issue by chazzaoui** [snowplow-incubator/snowplow-react-native-tracker#95] opened 2020-10-19 10:59 UTC
**Describe the bug**
Android is not tracking events when initialized. First I thought this was a setup issue, but noticed the same problem in the demo app. Works for ios.

**To Reproduce**
Install demoapp, set endpoint to localhost:3000,  setup nepsnowplow to check for events. No events displayed. For android, does show for ios

**Expected behavior**
Expect android to also display screen events. When the app is initialized al the events work for Ios but not for android. This same behaviour is also seen in the demo app.

**Smartphone (please complete the following information):**
 - Device: Multiple Android emulators and a samsung S9
 - OS: android studio 4.0.2
 - Version: @snowplow/react-native-tracker": "^0.1.1"
 - react native: 0.62.2

Here a link to the video showing the issue:
https://twitter.com/ChaffieRN/status/1318146130388148225?s=20

**Comment by colmsnowplow** [comment] 2020-10-20 10:11
Hi @chazzaoui, thanks for the report.

I can't reproduce the issue, both Android and iOS are working fine from my side. 

I am using a Snowplow Mini instance to test, however, which leads me to believe that the issue for you might be down to communicating with localhost. I know there [can be fiddly things with permissions](https://stackoverflow.com/questions/6760585/accessing-localhostport-from-android-emulator/9515414#9515414) needed.

If that doesn't solve the problem it's worth testing using something like [Snowplow Mini](https://github.com/snowplow/snowplow-mini) if possible, to see if it persists on an external endpoint.

Closing this issue as it seems not to be a bug in the tracker. Please do reach out again if you discover reason to believe otherwise though. :)

**Closed as completed by colmsnowplow** 2020-10-20 10:11 UTC
Labels: type:defect

**Comment by chazzaoui** [comment] 2020-10-20 11:33
@colmsnowplow Thank you for the response. 
This would explain why it does work on Ios. Will check the permissions settings. 
Thank you!
