### ISSUE TITLE
Add Standard Settings

### ISSUE THREAD

**Issue by max-tgam** [snowplow-incubator/snowplow-react-native-tracker#34] opened 2020-03-25 15:27 UTC
Please add ability to enable the following Standard App Contexts:
- Session context (with Session tracking)
- Application context
- Platform context

@colmsnowplow I can do a PR for this. Please let me know if there is anything in particular that jumps out at you that I should be aware of.

I believe that the following might require additional integration but I can at least provide ability to turn them one (please let me know what you think):
- Foreground and background events
- Exception tracking
- Screen view tracking
- Install tracking
- Screen Context
- Geolocation context

**Comment by colmsnowplow** [comment] 2020-03-25 18:36
Hi @max-tgam! Thanks for raising.

Platform context is already enabled by default (I may have misled you on that one, apologies). Screen view tracking is already available (although auto tracking of screen Views doesn't work as intended and we plan to remove it for a beta/v1 - we may revisit and find some solution in future). 

As for the rest, we'd be happy to review a PR. Some of these might be harder than others - I'm a bit short on time to test atm, so I can only give you my hunches/notes off the top of my head:

For each method, we'll need them to be implemented for both Android and iOS, otherwise one can break the other.

- Session Context
- Application context
- Screen Context
- Foreground and background events
- Geolocation context


I think these are straightforward enough to add by extending the existing implementations of the initialize method [here for iOS](https://github.com/snowplow-incubator/snowplow-react-native-tracker/blob/6d95fc4bcd1b30a1ba0827c6b80210aaac3683f1/ios/RNSnowplowTracker.m#L17-L40) and [here for Android](https://github.com/snowplow-incubator/snowplow-react-native-tracker/blob/6d95fc4bcd1b30a1ba0827c6b80210aaac3683f1/android/src/main/java/com/snowplowanalytics/react/tracker/RNSnowplowTrackerModule.java#L37-L51).

They should be set by passing arguments in the options JSON {} of the initialize method (the way autoTrackScreenViews is currently), and they'll need defaults in case they're not set (Safest is to default them all to off to begin with).

- Install tracking
- Exception tracking

It might be possible to instrument these in the same way, but I'm unsure if they'll require an extra import or an extra bridging module, I'm not sure.

---

If you could please commit in a way that one commit affects no more than one method implementation, that'll make life easier when it comes to prepping the release. 

As for testing, you can build the asset via `npm pack`, then point to the asset that this creates on your machine when installing to the demo app.

Hope that's helpful, let me know if you have questions!

**Comment by max-tgam** [comment] 2020-03-25 19:27
@colmsnowplow This helps a lot. Thank you!

**Comment by max-tgam** [comment] 2020-04-01 15:00
@colmsnowplow How do I contribute to this repo? If I try to push to it I get permissions denied message.

**Comment by colmsnowplow** [comment] 2020-04-01 16:05
You'll need to create a PR from a fork of the repo, same way you would have for [this PR on the JS tracker](https://github.com/snowplow/snowplow-javascript-tracker/pull/747), for example.

I didn't anticipate contributions so early, so there's no `develop` branch yet - just create the PR into master and I can take it from there :) 

Let me know if that doesn't unblock!

**Comment by max-tgam** [comment] 2020-04-01 16:06
@colmsnowplow That unblocks it. Thanks!

**Comment by max-tgam** [comment] 2020-04-02 18:12
@colmsnowplow I created bunch of PRs. 
I tried to organize them logically while focusing on one specific common area. 
Then I also created one overarching PR that includes all of them.
What and how you want to merge them - up to you.

Here are some notes and links to PRs (I cannot add you as reviewer so flagging them here):

- Session Context and related configuration: https://github.com/snowplow-incubator/snowplow-react-native-tracker/pull/35
- Application Context: https://github.com/snowplow-incubator/snowplow-react-native-tracker/pull/36
- Life Cycle Events: https://github.com/snowplow-incubator/snowplow-react-native-tracker/pull/37
- Screen Context: https://github.com/snowplow-incubator/snowplow-react-native-tracker/pull/38
- Base64 config: https://github.com/snowplow-incubator/snowplow-react-native-tracker/pull/39 (this was not in original request above, I forgot to include it, I hope it is ok)
-  Install and Exception Events https://github.com/snowplow-incubator/snowplow-react-native-tracker/pull/40 Install works on iOS, on other it needs additional configuration, if you can point in. direction of where to look at - I can further try to instrument it or at least provide documentation on how to do it (I suspect this is related to App setup more than SDK code)
- Platform and Geo contexts: https://github.com/snowplow-incubator/snowplow-react-native-tracker/pull/41 - I know you have these already but it is nice to be able to configure those (So I added this). Geo contexts might need additional instrumentation (I suspect it is the same issue as with Exception tracking).
- Finally I added ability to set UserId. The iOS implementation is not ideal as it requires an extra parameter to maintain Platform and Geo context settings. It is here: https://github.com/snowplow-incubator/snowplow-react-native-tracker/pull/44

Finally one PR to rule them all is here https://github.com/snowplow-incubator/snowplow-react-native-tracker/pull/42.

I haven't added documentation jsut tried to make it as close to original iOS/Adndrod configuration as possible. I can add that but please let me know where it should go (i.e. should I just add it into `README.md`?)

**Comment by colmsnowplow** [comment] 2020-04-03 10:06
Thanks Max! Both PRs look good at first glance, appreciate the contribution.

Trying to squeeze some time into the sprint last minute so bear with me, hopefully if all goes well I can review, test and push out the release next week or shortly thereafter. :)

**Comment by colmsnowplow** [comment] 2020-04-09 18:41
Hey @max-tgam, [PR is here](https://github.com/snowplow-incubator/snowplow-react-native-tracker/pull/49) - I'll get it reviewed next week then will release. 

A couple of notes FYI:

- Geolocation context works differently on each platform in the native trackers, and iOS needs work. 

I've left it out until those issues are resolved in the native trackers.

- Exception tracking didn't work as expected, so I removed it. 

I spent some time trying to create test scenarios for it, but it proved to be costing a lot of time, so I just ripped it out in the name of getting a release done.

- I moved all of the subject settings out of the initialise method, including set userid. 

Technically if we want to mirror the mobile trackers exactly, some of them should be settable both ways, however there's no difference in practice (you can just set the subject straight after initialisation). This way this project only needs to maintain one thing that can go wrong, so for now it's the most pragmatic choice.

By the by, in the native trackers alterations to the subject will be picked up automatically (it's a persistent object and is pulled on each track method), so you can alter the subject at any time and any amount of times without needing to re-assign it to the tracker. I believe the instrumentation I've gone for fits all use cases.

Thanks again for the pr, it is much appreciated. Let me know if you'd like to be added to the package.json as a contributor, and if so what name you'd like me to use! (some people prefer not to use their real one).

**Comment by max-tgam** [comment] 2020-04-09 19:01
@colmsnowplow Thanks!

All changes makes sense to me. Changes for Geo and Exception are OK. We have not really seen a good use case for those anyway in apps. I thought of adding those since I was adding everything else.

For some reason when I was not getting subject prior to updating `userId` I saw the platform context disappear from data being sent on iOS (even though tracker was initialized with platform context enabled). I think it was related to how I was setting the userId.

In terms of being added as a contributor - sure I'd love to be added. And it is OK to use my real name.

**Comment by colmsnowplow** [comment] 2020-04-09 19:19
So I think the logic you had was something like:

```
subject1 = [create subject with platform context]

tracker.useSubject1

subject2 = [create subject with userid]

tracker.useSubject2
```

So basically the previous settings were overwritten when you added a userid. New logic creates a subject on initialisation, then the setSubjectData calls the tracker to update configuration of the same subject. :)

**Comment by max-tgam** [comment] 2020-04-09 19:22
Yeah. that is correct. It was really difficult to find reliable documentation on how to modify subject for iOS as the latest documentation doesn't have it (I think documentation for 0.0.7 has it but not anything after)

**Comment by colmsnowplow** [comment] 2020-04-09 19:31
Yes, the docs do need work, apologies for that. We've moved to a [new docs site](https://docs.snowplowanalytics.com/docs/collecting-data/collecting-from-own-applications/objective-c-tracker/) and we're working on it!

**Comment by max-tgam** [comment] 2020-04-09 19:46
Yes, no worries, I figured, just saying that it was part of the reason I had such an odd implementation.

**Closed as completed** 2020-04-16 20:38 UTC
