### ISSUE TITLE
Custom headers not possible in react native tracker

### ISSUE THREAD

**Issue by shalinibnair** [snowplow-incubator/snowplow-react-native-tracker#166] opened 2022-08-17 11:31 UTC
We need to send auth details as part of header to make the collector secure.

The solution for this was already added in js tracker
https://github.com/snowplow/snowplow-javascript-tracker/issues/1010

But the same is missing in react native

**Comment by matus-tomlein** [comment] 2022-09-12 12:55
This is a duplicate of #165, closing.

**Closed as completed by matus-tomlein** 2022-09-12 12:55 UTC
