### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by tromika** [snowplow-incubator/snowplow-react-native-tracker#67] opened 2020-05-28 14:02 UTC
Hi there,

Please could you add a license to the project? As we're following this tracker closely to be inspired and coming up with a Flutter tracker at the end.
I'd avoid any issue with your license.

Thanks in advance!

**Comment by colmsnowplow** [comment] 2020-06-03 18:14
Hey @tromika - closing this as it's a duplicate of #62. Next release will add a licence (apologies one wasn't added before!)

The idea of a flutter tracker is one we've kicked around for a while also - but has not as yet made it to the roadmap. We'd be very interested in seeing how you get on with it!

**Closed as completed by colmsnowplow** 2020-06-03 18:14 UTC

**Comment by tromika** [comment] 2020-06-04 07:50
Thanks @colmsnowplow, sry somehow I didn't notice that....

**Comment by colmsnowplow** [comment] 2020-06-04 08:32
Not a problem at all! 

I'm always happy for people to open an issue and make sure things are reported - if it's a dupe it's no trouble to close them. :)
