### ISSUE TITLE
Large number of crashed sessions on Android

### ISSUE THREAD

**Issue by jdmunro** [snowplow-incubator/snowplow-react-native-tracker#65] opened 2020-05-21 08:53 UTC
Package version: `0.1.0-alpha.16`

We recently launched an updated version of our React Native app with snowplow tracking enabled. Over the following days we observed a significant increase in the number of crashed sessions, with the following stack trace:

<img width="982" alt="Screenshot 2020-05-21 at 09 43 35" src="https://user-images.githubusercontent.com/17656/82540920-8f74c800-9b47-11ea-92c1-84ddce094b02.png">

Ultimately crashing on this line: https://github.com/snowplow/snowplow-android-tracker/blob/0ab5eeaf15eea7ca9562cf96dd28a034b97c668c/snowplow-tracker/src/main/java/com/snowplowanalytics/snowplow/tracker/Tracker.java#L91

After a couple of wrong turns we were able to come up with the following process for reproducing it:

1. Freshly install the app
2. Open the app and see if it crashes
3. If not, delete app and restart the process

This gives us a crash rate of approximately 20% on launching the app for the first time. Once the app has successfully opened once, we are unable to reproduce the problem further.

Whilst the the problem is in the native Android snowplow tracker, I suspect the problem actually lies in the way the RN bindings interact with it. We speculate that this is probably a threading issue, [from the official docs](https://reactnative.dev/docs/native-modules-android#threading):

> Native modules should not have any assumptions about what thread they are being called on, as the current assignment is subject to change in the future.

We suspect something is going awry with the install tracking and how it calls back into the main instance here: https://github.com/snowplow/snowplow-android-tracker/blob/master/snowplow-tracker/src/main/java/com/snowplowanalytics/snowplow/tracker/tracker/InstallTracker.java#L99

Which is initially triggered in the constructor of that instance: https://github.com/snowplow/snowplow-android-tracker/blob/master/snowplow-tracker/src/main/java/com/snowplowanalytics/snowplow/tracker/Tracker.java#L465

### Workaround

For now, we have `setInstallEvent` set to `false` and this has resolved the problem for us by short-circuiting the install tracking.

**Comment by colmsnowplow** [comment] 2020-05-21 12:45
Thanks for reporting @jdmunro. 

Short term, the most obvious thing to do seems to be to remove install tracking from react-native for now, unless we can come up with a way to make it stable.

Longer term I'll knock heads together with the team to see if there's a solution to be found in the native tracker(s).

**Comment by colmsnowplow** [comment] 2020-06-05 11:49
Quick update on this one - a patch for the crashing itself [is in the latest release of the Android tracker](https://github.com/snowplow/snowplow-android-tracker/issues/377). 

So bumping to that version is one option for an immediate workaround. 

However while this will prevent crashes, the cases where it currently crash would still lead to missing install events unfortunately - this is something we're looking for a solution for also.

**Comment by colmsnowplow** [comment] 2020-06-10 19:50
Android version is [actually already configured](https://github.com/snowplow-incubator/snowplow-react-native-tracker/commit/a914515e7d7997c33a017a44afeee09c11c04575) to use the latest 1.X tracker - so actually no changes required for the patch.

Indeed I've been unable to reproduce the error in my tests since that release.

Closing this issue - @jdmunro please let us know if the issue persists for you after rebuilding dependencies.

**Closed as completed by colmsnowplow** 2020-06-10 19:50 UTC
Labels: type:defect
