### ISSUE TITLE
Android app crashes immediately after installing @snowplow/react-native-tracker

### ISSUE THREAD

**Issue by sbycrosz** [snowplow-incubator/snowplow-react-native-tracker#135] opened 2021-12-17 08:51 UTC
**Describe the bug**

Android app crashes immediately after installing `@snowplow/react-native-tracker`

```
12-17 16:24:21.393 22183 22287 E AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
12-17 16:24:21.393 22183 22287 E AndroidRuntime: Process: com.stashaway.dev2, PID: 22183
12-17 16:24:21.393 22183 22287 E AndroidRuntime: java.lang.NoSuchMethodError: No static method delimiterOffset(Ljava/lang/String;IILjava/lang/String;)I in class Lokhttp3/internal/Util; or its super classes (declaration of 'okhttp3.internal.Util' appears in /data/app/~~Knx0lR0kGEb4a3S6JyqZlA==/com.stashaway.dev2-veK5P-7t4ksEHivqmC8n1w==/base.apk!classes4.dex)
```

**To Reproduce**

1. `yarn add @snowplow/react-native-tracker`
2. `yarn run-android`
3. App crashes immediately after launch

**Expected behavior**

Android app shouldn't crash at launch

**Screenshots**
NA

**Device information**
 - Device: Android emulator
 - OS: Android 10
 - react-native@0.62.2
 - @snowplow/react-native-tracker@1.0.0"

**Comment by adatzer** [comment] 2021-12-17 15:08
Hi @sbycrosz, and thank you for the report! 
We suspect an okhttp version mismatch, but didn't get to reproduce the crash based on the above information.
Is there a reproducible example that you can share, or would you be able to post your app's dependencies in your `build.gradle` file or check your `./gradlew :app:dependencies` tree, to help us get to the cause of the issue?

**Comment by sbycrosz** [comment] 2022-02-10 09:04
Hi, sorry for a very late response

`./gradlew :app:dependencies` returns [this](https://gist.github.com/sbycrosz/592e9288c46ac873d6ddaa3dc7fb325f)

I'm going to try the latest snowplow/react-native-tracker shortly and see if that fixes this

Cheers!

**Comment by AlexBenny** [comment] 2022-02-17 09:43
Hi @sbycrosz ,

We noticed that in the list of dependencies you shared doesn't appear the snowplow tracker.
Perhaps you removed it for some experiments?

In your dependencies list, OkHttp has been bumped from v3.12.1 to v4.9.1.
I think the reason is that `com.facebook.fresco:imagepipeline-okhttp3:2.5.0` uses internally OkHttp v3.12.1 while `com.facebook.react:react-native:+ -> 0.66.4` uses internally OkHttp v4.9.1.
In these cases, Gradle selects the highest version, hence OkHttp v4.9.1.

Though, this has been very helpful for us to spot a source of conflict in our tracker too. The Snowplow React Native Tracker uses internally the native Android Tracker that makes use of OkHttp v4.9.1 for the networking.
Despite we haven't been able to reproduce the issue reliably we discovered that React Native uses internally OkHttp and [they bumped from v3 to v4](https://reactnative.dev/blog/2021/08/17/version-065#notable-dependency-version-updates-and-gotchas) in the version 0.65. We tested our tracker with v0.59 without problems but actually the  min supported version should be v0.65.

We are going to update our documentation informing that the React Native Tracker will support v0.65+ rather than v0.59+.

In your specific case I would suggest to check the OkHttp version used by the various frameworks.
Using `fresco:imagepipeline` you should use a React Native version <0.65 and our Snowplow React Native Tracker v0.2.
If you are able to update your app to use React Native version 0.65+, you can make use of our last version of our React Native Tracker.

Please, let us know if you have new info on this issue and thanks for sharing with us.

**Comment by AlexBenny** [comment] 2022-03-30 16:22
Closing the issue as the new [React Native Tracker v1.2](https://github.com/snowplow/snowplow-react-native-tracker/releases/tag/1.2.0) sets the React Native minimum supported version to v0.65 in order to avoid conflicts with OkHttp lib (dependency of React Native and Snowplow Android Tracker).
Please, feel free to reopen this issue if the problem persist with the new tracker version.

**Closed as completed by AlexBenny** 2022-03-30 16:22 UTC
Labels: type:defect
